[build]
  # Directory to build from
  publish = "build"
  # Build command
  command = "npm run build"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (will be set via Netlify UI)
[build.environment]
  REACT_APP_API_URL = "https://tcs-roster-mobile-1.onrender.com"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"